### PR TITLE
added custom tracker for facebook custom audiences

### PR DESCRIPTION
**Pull request by thelonecabbage**
Added angulartics-facebook for tracking page views and events for facebooks custom audience website.

https://developers.facebook.com/docs/reference/ads-api/custom-audience-website/

[Review on Reviewable](https://reviewable.io/reviews/chrismendis/angulartics/1)

### CODE REVIEW

**Comment by thelonecabbage** [comment]
hello?

**Comment by chrismendis** [comment]
Sorry @thelonecabbage, I don't think I ever got a notification for this PR. My bad! Did you mean to make a PR off of my branch or the repo I originally forked (https://github.com/hekike/angulartics)?

**Comment by thelonecabbage** [comment]
PR off your branch.  I don't imagine anyone would use FB custom audiences, rather than ga. It almost requires working with multiple services.

**Comment by chrismendis** [comment]
hekike's fork of angulartics has support for multiple services: https://github.com/hekike/angulartics/blob/master/src/angulartics.js#L71. My fork of simply adds ui-router support to his fork.

I'm happy to merge in your PR, if you'd like to keep using my fork.

**Pull request closed without merging**
